# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  # github: "#"
  # weibo: "#"
  # rss: "#"
  # zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 友言
uyan_id: 2128624
uyan_du: www.qtdebug.com

#是否开启打赏功能
donate: false
#打赏文案
donate_message: 欣赏此文？求鼓励，求支持！

# Content
excerpt_link: 阅读全文
fancybox: true
mathjax: false

# 是否开启动画效果
animate: false

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /img/dog.png

#你的头像url
avatar: /img/dog.png
#是否开启分享

#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  华夏大地教育网: http://www.edu-edu.com

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 吞风吻雨葬落日未曾彷徨，欺山赶海践雪径也未绝望，拈花把酒偏折煞世人情狂，凭这两眼与百臂或千手不能防，天阔阔雪漫漫共谁同航，这沙滚滚水皱皱笑着浪荡，贪欢一晌偏教那女儿情长埋葬。
